# Generated by Django 4.2.1 on 2023-05-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("loans", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="customerloan",
            name="amount",
            field=models.IntegerField(default=6000),
            preserve_default=False,
        )
    ]
